### ISSUE TITLE
CORS policy problem

### ISSUE THREAD

**Issue by abodehq** [jin-qu/linquest#11]
Access to fetch at 'http://localhost:55106/admin/api/v1/apps/1/categories/1' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

Can you please provide an example how we can allow origin for the request 
const service = new ODataService ("http://localhost:55106/admin/api/v1/apps/1/")
const books = await service
    .createQuery(Category)
    .toArrayAsync()

thanks

**Comment by umutozel** [comment]
Probably same as https://github.com/jin-qu/jinqu-odata/issues/29 :)
